export enum GlobalRoutes {
  Home = "/",
  Login = "/login",
  Register = "/register",
  Dashboard = "/dashboard",
  DashboardExplore = "/dashboard/explore",
  DashboardHome = "",
  DashboardProfile = "/dashboard/:profile",
  DashboardIndividualPost = "/dashboard/:profile/post/:postID",
  ProfilePosts = "posts",
  ProfileReels = "reels",
  ProfileBookmarks = "bookmarks",
  DashboardProfileEdit = "/dashboard/profile/edit",
  DashboardMessages = "/dashboard/messages",
  DashboardReels = "/dashboard/reels",
  ForgotPassword = "/forgot-password",
  ResetPassword = "/reset-password",
  DashboardNotifications = "/dashboard/notifications",
  NotFound = "*",
}
